[params]
  baseURL = 'https://uhctf.github.io/uhctf.be/'

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "pink"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 555

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "UHCTF"
    subtitle = "UHasselt Capture The Flag"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "UHCTF"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 100
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        weight = 200
        identifier = "Pratical"
        name = "Practical"
        url = "/practical"
      [[languages.en.menu.main]]
        weight = 300
        identifier = "Previous editions"
        name = "Previous Editions"
        url = "/previous"
      [[languages.en.menu.main]]
        weight = 400
        identifier = "Tips"
        name = "Tips"
        url = "/tips"
      #[[languages.en.menu.main]]
      #  weight = 600
      #  identifier = "Scoreboard"
      #  name = "Scoreboard"
      #  url = "https://score.uhctf.be"
      [[languages.en.menu.main]]
        weight = 700
        identifier = "sponsor"
        name = "Sponsors"
        url = "/sponsors"
      [[languages.en.menu.main]]
        identifier = "contact"
        weight = 1000
        name = "Contact"
        url = "/contact"

[module]
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
