name: ðŸš€ Deploy website on main push
on:
  push:
    branches:
      - main
  schedule: 
    - cron: '5 1 * * *'
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-22.04
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.139.3'
        extended: true
    - name: Build
      run: hugo --minify
    - name: ðŸ“‚ Sync files
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        localDir: "public/"
        remoteDir: "uhctf-be"
        host: ${{ secrets.FTP_SRV }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
